### ISSUE TITLE
There's a fatal error in your code

### ISSUE THREAD

**Issue by foresee-io** [mayali123/snake#1]
拿来学习学习√get 不过用vs2019的时候出了问题：
代码366行p-> !=NULL明显是错的，猜你应该想表达p->next；
另外呢，如果磁盘相应位置没有save.txt，运行就会出bug（这个问题本人也在纠结）

**Comment by mayali123** [comment]
磁盘相应位置没有save.txt，运行会出错，是因为我有对save.txt的写入和读取得操作，也就是fprintf()和fscanf(),那个366行p-> !=NULL这个是你说得那样。
